In [1]:
import pandas as pd
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [29]:
data={"mats":75,
      "chemistry":80,
      "physics":87}
s=pd.Series(data)
print(s)

mats         75
chemistry    80
physics      87
dtype: int64

In [30]:
s=pd.Series([10,20,30],index=['A','B','C'])
print(s)

A    10
B    20
C    30
dtype: int64

In [31]:
s=pd.Series([11,22,33,44])
print(s.size)
print(s.shape)
print(s.dtype)

4
(4,)
int64

In [32]:
s=pd.Series([10,20,30,40,50])
print(s+10)
print(s*2)

0    20
1    30
2    40
3    50
4    60
dtype: int64
0     20
1     40
2     60
3     80
4    100
dtype: int64

In [33]:
s=pd.Series([12,22,32,42,52])
print("Sum=",s.sum())
print("Mean=",s.mean())
print("Maximum=",s.max())
print("Minimum=",s.min())

Sum= 160
Mean= 32.0
Maximum= 52
Minimum= 12

In [49]:
data={
    'Rollno':[101,102,103,104,105,106,10,108,109,110],
    'Name':['Arun','Priya','Rahul','anantha','nitin','sundar','mani','agash','arivu','nithish'],
    'Marks':[85,90,78,80,80,80,80,80,80,80]}
df=pd.DataFrame(data)
print(df)
print(df.columns)
print(df.index)
print(df.dtypes)

   Rollno     Name  Marks
0     101     Arun     85
1     102    Priya     90
2     103    Rahul     78
3     104  anantha     80
4     105    nitin     80
5     106   sundar     80
6      10     mani     80
7     108    agash     80
8     109    arivu     80
9     110  nithish     80
Index(['Rollno', 'Name', 'Marks'], dtype='object')
RangeIndex(start=0, stop=10, step=1)
Rollno     int64
Name      object
Marks      int64
dtype: object

In [51]:
df=pd.DataFrame(data,index=['A','B','C','A','A','A','A','A','A','A'])
print(df)

   Rollno     Name  Marks
A     101     Arun     85
B     102    Priya     90
C     103    Rahul     78
A     104  anantha     80
A     105    nitin     80
A     106   sundar     80
A      10     mani     80
A     108    agash     80
A     109    arivu     80
A     110  nithish     80

In [53]:
df['Grade']=['A','A+','C','A','A','A','A','A','A','A']
print(df[['Name','Marks']])

      Name  Marks
A     Arun     85
B    Priya     90
C    Rahul     78
A  anantha     80
A    nitin     80
A   sundar     80
A     mani     80
A    agash     80
A    arivu     80
A  nithish     80

In [39]:
print(df.iloc[0])
print(df.iloc[[0,2]])
print(df.iloc[1])
print(df.iloc[[0,2]])

Rollno     101
Name      Arun
Marks       85
Grade        A
Name: A, dtype: object
   Rollno   Name  Marks Grade
A     101   Arun     85     A
C     103  Rahul     78     C
Rollno      102
Name      Priya
Marks        90
Grade        A+
Name: B, dtype: object
   Rollno   Name  Marks Grade
A     101   Arun     85     A
C     103  Rahul     78     C

In [54]:
df['Marks']=df['Marks']+5
print(df)

   Rollno     Name  Marks Grade
A     101     Arun     90     A
B     102    Priya     95    A+
C     103    Rahul     83     C
A     104  anantha     85     A
A     105    nitin     85     A
A     106   sundar     85     A
A      10     mani     85     A
A     108    agash     85     A
A     109    arivu     85     A
A     110  nithish     85     A

In [55]:
print(df)

   Rollno     Name  Marks Grade
A     101     Arun     90     A
B     102    Priya     95    A+
C     103    Rahul     83     C
A     104  anantha     85     A
A     105    nitin     85     A
A     106   sundar     85     A
A      10     mani     85     A
A     108    agash     85     A
A     109    arivu     85     A
A     110  nithish     85     A

In [56]:
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].min())
print(df['Marks'].sum())

86.3
95
83
863

In [57]:
df.drop('Grade',
       axis=1,
       inplace=True)
print(df)

   Rollno     Name  Marks
A     101     Arun     90
B     102    Priya     95
C     103    Rahul     83
A     104  anantha     85
A     105    nitin     85
A     106   sundar     85
A      10     mani     85
A     108    agash     85
A     109    arivu     85
A     110  nithish     85

In [58]:
df.sort_values('Marks',
               ascending=False)

   Rollno     Name  Marks
B     102    Priya     95
A     101     Arun     90
A     104  anantha     85
A     105    nitin     85
A     106   sundar     85
A      10     mani     85
A     108    agash     85
A     109    arivu     85
A     110  nithish     85
C     103    Rahul     83

In [59]:
df.head()

   Rollno     Name  Marks
A     101     Arun     90
B     102    Priya     95
C     103    Rahul     83
A     104  anantha     85
A     105    nitin     85

In [60]:
df.tail()

   Rollno     Name  Marks
A     106   sundar     85
A      10     mani     85
A     108    agash     85
A     109    arivu     85
A     110  nithish     85

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, A to A
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rollno  10 non-null     int64
 1   Name    10 non-null     object
 2   Marks   10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes

In [71]:
data={
    'Roll number':[1,2,3,4,5,6,7,8,9,10],
    'Name':['a','b','c','d','e','f','g','h','i','j'],
    'Marks':[81,82,83,84,85,86,87,88,89,90]
}
fd=pd.DataFrame(data)
print(fd)

   Roll number Name  Marks
0            1    a     81
1            2    b     82
2            3    c     83
3            4    d     84
4            5    e     85
5            6    f     86
6            7    g     87
7            8    h     88
8            9    i     89
9           10    j     90

In [73]:
print(fd['Marks'].mean())
print(fd['Marks'].max())
print(fd['Marks'].min())
print(fd['Marks'].sum())

85.5
90
81
855

In [74]:
data={
    'Empolyee Name':['a','b','c','d','e','f','g','h','i','j'],
    'Salary':[30000,35000,38000,40000,42000,45000,32000,48000,33000,37000,]    
}
ds=pd.DataFrame(data)
print(ds)

  Empolyee Name  Salary
0             a   30000
1             b   35000
2             c   38000
3             d   40000
4             e   42000
5             f   45000
6             g   32000
7             h   48000
8             i   33000
9             j   37000

In [17]:
af=pd.read_csv("Students.csv")
print(af)

   Roll No   Name Department  Marks
0      101   Arun        CSE     85
1      102  Priya         Ai     92
2      103  Rahul         IT     78
3      104  Divya        CSE     88

In [18]:
print(af.iloc[1])

Roll No         102
Name          Priya
Department       Ai
Marks            92
Name: 1, dtype: object

In [20]:
af['Marks']=af['Marks']+5
print(af)

   Roll No   Name Department  Marks
0      101   Arun        CSE     90
1      102  Priya         Ai     97
2      103  Rahul         IT     83
3      104  Divya        CSE     93